//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class Path
{
	public List<Vector3>waypoints = new List<Vector3>();
	public bool looped;
	 public int next;
	public Path ()
	{
		looped = false;
		next = 0;
	}

	public Vector3 NextWaypint()
	   {

		if (next < waypoints.Count) 
		{
			return waypoints [next];
		} 
		else
		{
			return Vector3.zero;		
		}
	
        }

  public	void Advance(){
		if (looped) {
						next = (next + 1) % waypoints.Count;
				}
		else 
		{ 
			if(next < (waypoints.Count -1 )){
				next++;
			}
		}
	}
	public bool islast(){
		return ((! looped) && (next == waypoints.Count - 1));
	}

}

